controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# api_register:
#   path: /api/auth/register
#   controller: App\Controller\Security\AuthController::register
#   methods: [POST]

# api_login_check:
#   path: /api/auth/login
#   controller: App\Controller\Security\AuthController::login
#   methods: [POST]

api_token_refresh:
  path: /api/auth/token/refresh
  methods: [POST]

api_verify_email:
  path: /api/auth/verify-email/{token}
  controller: App\Controller\Security\EmailVerificationController::verifyEmail
  methods: [GET]

app_auth_verify_email:
  path: /auth/verify-email/{token}
  controller: App\Controller\Security\AuthController::verifyEmail
  methods: [POST]
