security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Security\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern: ^/auth/login
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /auth/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        username_path: email
        password_path: password
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~
    main:
      lazy: true
      provider: app_user_provider
      json_login:
        check_path: /auth/login
        username_path: email
        password_path: password
      stateless: true
      jwt: ~

  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/auth/register, roles: PUBLIC_ACCESS }
    - { path: ^/password-reset, roles: PUBLIC_ACCESS }
    - { path: ^/auth/verify-email, roles: PUBLIC_ACCESS }
    - { path: ^/auth/me, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api/competitions, roles: PUBLIC_ACCESS }
    - { path: ^/users/update/password, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost:
        memory_cost: 10
