import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBell,
  faCalendar,
  faChartBar,
  faCircleCheck,
  faCirclePause,
  faCirclePlay,
  faCircleQuestion,
  faCircleUser,
  faCircleXmark,
  faClock,
  faComment,
  faCopy,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFileLines,
  faFlag,
  faHourglass,
  faIdCard,
  faImage,
  faMap,
  faPaperPlane,
  faPenToSquare,
  faRectangleList,
  faStar,
  faUser,
} from '@fortawesome/free-regular-svg-icons';
import {
  faBars,
  faBell as faBellSolid,
  faBookOpen,
  faCamera,
  faCheck,
  faChevronLeft,
  faEnvelope as faEnvelopeSolid,
  faFileLines as faFileLinesSolid,
  faFilePdf,
  faFlagCheckered,
  faGear,
  faHouse,
  faKey,
  faLock,
  faPlus,
  faRectangleList as faRectangleListSolid,
  faRightFromBracket,
  faRocket,
  faTrophy,
  faUser as faUserSolid,
  faUserPlus,
  faUsers,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

library.add(
  faBell,
  faCalendar,
  faChartBar,
  faCircleCheck,
  faCirclePause,
  faCirclePlay,
  faCircleQuestion,
  faCircleUser,
  faCircleXmark,
  faClock,
  faComment,
  faCopy,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFileLines,
  faFlag,
  faHourglass,
  faIdCard,
  faImage,
  faMap,
  faPaperPlane,
  faPenToSquare,
  faRectangleList,
  faStar,
  faUser,
  faBars,
  faBellSolid,
  faBookOpen,
  faCamera,
  faCheck,
  faChevronLeft,
  faEnvelopeSolid,
  faFileLinesSolid,
  faFilePdf,
  faFlagCheckered,
  faGear,
  faHouse,
  faKey,
  faLock,
  faPlus,
  faRectangleListSolid,
  faRightFromBracket,
  faRocket,
  faTrophy,
  faUserSolid,
  faUserPlus,
  faUsers,
  faXmark
);

/** Regular pour le reste de l’app ; Solid pour le menu burger (user, bell, envelope, historique, fichier). */
export const appIcons = {
  home: faHouse,
  user: faUserSolid,
  userCircle: faCircleUser,
  history: faRectangleListSolid,
  bell: faBellSolid,
  envelope: faEnvelopeSolid,
  gear: faGear,
  file: faFileLinesSolid,
  key: faKey,
  register: faUserPlus,
  logout: faRightFromBracket,
  back: faChevronLeft,
  menu: faBars,
  close: faXmark,
  camera: faCamera,
  trophy: faTrophy,
  users: faUsers,
  check: faCheck,
  chart: faChartBar,
  book: faBookOpen,
  eye: faEye,
  eyeSlash: faEyeSlash,
  help: faCircleQuestion,
  plus: faPlus,
  lock: faLock,
  pause: faCirclePause,
  play: faCirclePlay,
  clock: faClock,
  hourglass: faHourglass,
  rocket: faRocket,
  flag: faFlag,
  flagCheckered: faFlagCheckered,
  map: faMap,
  image: faImage,
  comment: faComment,
  calendar: faCalendar,
  paperPlane: faPaperPlane,
  edit: faPenToSquare,
  idCard: faIdCard,
  star: faStar,
  copy: faCopy,
  circleCheck: faCircleCheck,
  circleXmark: faCircleXmark,
  /** Regular `fa-file-pdf` n'existe pas dans le pack gratuit FA 7 — Solid. */
  filePdf: faFilePdf,
} as const satisfies Record<string, IconDefinition>;

export type AppIconName = keyof typeof appIcons;
